export const adminRagIngestionFormCopy = {
  en: {
    bulkIngest: "Ingest dictionary + grammar JSON",
    bulkIngesting: "Ingesting dictionary + grammar JSON...",
    checking: "Checking RAG services...",
    chunkDetails: "Chunk details",
    chunkProfile: "Chunk Profile",
    chunks: "chunks",
    chunksLabel: "Chunks",
    defaultChunkProfile:
      "Default chunk profile: 1600 chars target with 200 chars overlap.",
    embeddingBatches: "Embedding batches",
    embeddingProvider: "Embedding provider",
    entries: "entries",
    estimatedTokensPerChunk: "Est. tokens per chunk (min / avg / max)",
    estimatedTokensTotal: "Est. tokens total",
    failedJsonSources: "Failed JSON sources",
    fileIngest: "Ingest file into RAG",
    fileIngesting: "Indexing file into RAG...",
    forceOcr: "Force OCR for PDF extraction (bypass native PDF text)",
    insertBatches: "Insert batches",
    liveLogs: "Live logs are streaming for request",
    logs: "Logs",
    logsEmpty:
      "No ingestion logs yet. Run file or JSON ingestion to populate this stream.",
    logsRunning:
      "Ingestion is running. Logs will appear here as batches complete.",
    loadError: "Could not load RAG status.",
    ocrNo: "no",
    ocrUsed: "OCR used",
    ocrYes: "yes",
    overlapOverhead: "Overlap overhead",
    partialFailures: "Partial Failures",
    provider: "Provider",
    refresh: "Refresh",
    requestId: "Request ID",
    sourceLabel: "Source label",
    sources: "Sources",
    sourceTextChars: "Source text chars (normalized)",
    succeeded: "succeeded",
    supports: "Supports PDF, DOCX, images (OCR), and text-like files.",
    systemStatus: "System Status",
    targetOverlap: "Target size / overlap",
    totalChunkChars: "Total chunk chars stored",
    totalChunks: "Total chunks",
    unknownError: "Unknown error",
    unknownRequestError: "Unknown ingestion request error.",
    uploadError: "Could not ingest this file.",
    jsonError: "Could not ingest dictionary and grammar JSON files.",
    knowledgeFile: "Knowledge file",
    minAvgMaxChunkChars: "Min / Avg / Max chunk chars",
    minAvgMaxChunkWords: "Min / Avg / Max chunk words",
    runOcr: "Run OCR when PDF text extraction is weak",
    size: "size",
  },
  nl: {
    bulkIngest: "Woordenboek- en grammatica-JSON invoeren",
    bulkIngesting: "Woordenboek- en grammatica-JSON wordt ingevoerd...",
    checking: "RAG-services worden gecontroleerd...",
    chunkDetails: "Chunkdetails",
    chunkProfile: "Chunkprofiel",
    chunks: "chunks",
    chunksLabel: "Chunks",
    defaultChunkProfile:
      "Standaard chunkprofiel: doel van 1600 tekens met 200 tekens overlap.",
    embeddingBatches: "Embeddingbatches",
    embeddingProvider: "Embeddingprovider",
    entries: "items",
    estimatedTokensPerChunk: "Geschatte tokens per chunk (min / gem. / max)",
    estimatedTokensTotal: "Geschatte tokens totaal",
    failedJsonSources: "Mislukte JSON-bronnen",
    fileIngest: "Bestand in RAG invoeren",
    fileIngesting: "Bestand wordt in RAG geindexeerd...",
    forceOcr: "OCR forceren voor PDF-extractie (native PDF-tekst overslaan)",
    insertBatches: "Invoegbatches",
    liveLogs: "Live logs streamen voor request",
    logs: "Logs",
    logsEmpty:
      "Nog geen invoerlogs. Start bestands- of JSON-invoer om deze stream te vullen.",
    logsRunning:
      "Invoer loopt. Logs verschijnen hier zodra batches klaar zijn.",
    loadError: "RAG-status kon niet worden geladen.",
    ocrNo: "nee",
    ocrUsed: "OCR gebruikt",
    ocrYes: "ja",
    overlapOverhead: "Overlapoverhead",
    partialFailures: "Gedeeltelijke fouten",
    provider: "Provider",
    refresh: "Vernieuwen",
    requestId: "Request-ID",
    sourceLabel: "Bronlabel",
    sources: "Bronnen",
    sourceTextChars: "Bronteksttekens (genormaliseerd)",
    succeeded: "geslaagd",
    supports:
      "Ondersteunt PDF, DOCX, afbeeldingen (OCR) en tekstachtige bestanden.",
    systemStatus: "Systeemstatus",
    targetOverlap: "Doelgrootte / overlap",
    totalChunkChars: "Totaal opgeslagen chunktekens",
    totalChunks: "Totaal aantal chunks",
    unknownError: "Onbekende fout",
    unknownRequestError: "Onbekende invoerrequestfout.",
    uploadError: "Dit bestand kon niet worden ingevoerd.",
    jsonError:
      "Woordenboek- en grammatica-JSON-bestanden konden niet worden ingevoerd.",
    knowledgeFile: "Kennisbestand",
    minAvgMaxChunkChars: "Min / Gem. / Max chunktekens",
    minAvgMaxChunkWords: "Min / Gem. / Max chunkwoorden",
    runOcr: "OCR uitvoeren wanneer PDF-tekstextractie zwak is",
    size: "grootte",
  },
} as const;

export type AdminRagIngestionCopy =
  (typeof adminRagIngestionFormCopy)[keyof typeof adminRagIngestionFormCopy];
