import type { Language } from "@/types/i18n";

export const SHENUTE_COPY = {
  en: {
    accessRequired: "Please sign in to access Shenute AI.",
    addImage: "Add Image",
    adminNotePlaceholder:
      "Admin only: add corrected guidance tied to this prompt and response.",
    adminNoteSummary: "Admin learning note",
    aiMode: "Answer style",
    aiModeDescription: "Choose how Shenute should balance depth and speed.",
    answerStyleControls: "Change answer style",
    assistantLabel: "Shenute",
    attachmentHelp:
      "Shenute will read this image with OCR when you send your message.",
    attachmentName: "File",
    attachmentReady: "Image ready for OCR",
    attachmentSize: "Size",
    cameraCapture: "Capture Image",
    cameraClose: "Close Camera",
    cameraFrameFailed: "Could not capture camera frame.",
    cameraImageFailed: "Could not capture image from camera.",
    cameraNotReady: "Camera is not ready.",
    cameraPreview: "Camera preview",
    cameraNotSupported: "Camera is not supported on this device/browser.",
    cameraStillLoading: "Camera feed is not ready yet. Try again.",
    cameraSource: "camera",
    cancelResponse: "Stop response",
    closeMenu: "Close menu",
    closeAnswerStyleControls: "Close answer style controls",
    copiedResponse: "Copied.",
    conversationActions: "Conversation actions",
    conversationHistory: "Conversation history",
    copyResponse: "Copy",
    copyResponseFailed: "Could not copy response.",
    copyResponseManual: "Copy manually.",
    copyResponseManualHint:
      "Clipboard access is blocked in this browser. Select the response text below and copy it manually.",
    creditsLinkDescription:
      "Credits, technical notes, and research acknowledgements now live on the Contributors page.",
    creditsLinkTitle: "Credits and technical notes",
    creditsShort: "Credits",
    dangerZone: "Danger zone",
    dislike: "Not helpful",
    feedbackPromptMissing:
      "Could not resolve prompt/response for this feedback.",
    feedbackSaved: "Thanks for the feedback.",
    feedbackSavedWithRag: "Thanks, this helps improve Shenute.",
    feedbackSavedLearningDelayed:
      "Thanks for the feedback. The learning sync will catch up later.",
    feedbackSaveFailed: "Could not save feedback.",
    feedbackSaving: "Saving feedback...",
    feedbackSignIn: "Sign in to send feedback.",
    feedbackSignInInline: "Sign in to mark responses helpful.",
    expandControls: "Show chat controls",
    imageAttached: "Image attached",
    imageOcrContext: "[Image OCR Context]",
    intro:
      "Ask about Coptic vocabulary, grammar, translation, and manuscript context without leaving the shared app workspace.",
    jumpToLatest: "Latest",
    like: "Helpful",
    noTextExtracted: "No text extracted from the selected image.",
    ocrFailed: "OCR failed for the selected image.",
    pageContextBadge: "Page context",
    placeholder: "Ask about a Coptic word, grammar rule, or attached image...",
    placeholderImage: "Ask about this image...",
    placeholderShort: "Ask Shenute...",
    saveHistory: "Save now",
    saveHistorySaved: "Saved",
    savingHistory: "Saving...",
    savedHistory: "Conversation saved.",
    saveHistoryFailed: "Could not save this conversation.",
    historyUnavailable: "Conversation history could not load right now.",
    autosaveHint: "Conversations save automatically to your account.",
    autosaveStatus: "Saved to your account.",
    unsavedChanges: "Unsaved changes. Saving automatically...",
    clearConversation: "Delete conversation",
    clearConversationConfirm:
      "Delete this Shenute conversation? Saved copies will be removed from your account.",
    clearConversationFailed: "Could not delete this conversation.",
    clearingConversation: "Deleting conversation...",
    conversationCleared: "Conversation deleted.",
    continuePrompt: "Please continue your previous response.",
    continueResponse: "Continue answer",
    newConversation: "Start new chat",
    newConversationStarted: "New chat started.",
    thinking: "Thinking",
    thinkingComposing: "Composing answer",
    thinkingElapsed: "Elapsed",
    thinkingInitial: "Preparing answer",
    thinkingLong: "Still working",
    thinkingLongHint: "Larger Coptic questions can take a moment.",
    thinkingSearching: "Checking sources",
    loadSession: "Load",
    currentSession: "Current",
    loadingSession: "Loading session...",
    sessionCount: "sessions",
    sessionDateMissing: "No timestamp",
    sessionUnsavedBadge: "Unsaved",
    providerGemini: "Fast answer",
    providerGeminiDescription:
      "Use Gemini's own pretrained knowledge with retrieval as optional support.",
    providerGeminiNmt: "Fast answer (RAG + NMT)",
    providerGeminiNmtDescription:
      "Gemini with strict retrieved-context grounding plus NMT translation hints.",
    providerHf: "Experimental",
    providerHfDescription: "A lighter experimental pass for comparison.",
    providerOpenRouter: "Reasoned answer",
    providerOpenRouterDescription:
      "More step-by-step structure for harder questions.",
    providerThoth: "Best answer",
    providerThothDescription: "The strongest default for Coptology questions.",
    ragWarning: "Saved, but the learning sync warned:",
    rateLimit: "Shenute is busy right now. Please wait a moment and try again.",
    regenerateResponse: "Regenerate",
    remove: "Remove",
    requestFailed:
      "Shenute is having trouble answering right now. Please try again in a moment.",
    responseActions: "Response actions",
    responseFeedbackActions: "Feedback",
    responseReviseActions: "Revise answer",
    responseUseActions: "Use answer",
    runningOcr: "Running OCR...",
    selectCopyText: "Select text",
    sendMessage: "Send message",
    selectedImageAlt: "Selected for OCR",
    submitAdminNote: "Send admin note",
    starterPromptsTitle: "Try asking Shenute",
    starterPromptGrammar: "Explain how the Bohairic definite article works.",
    starterPromptImage: "Help me read a Coptic manuscript image.",
    starterPromptTranslate:
      "Translate “Jesus Christ is risen” into Bohairic Coptic.",
    title: "Shenute AI",
    uploadSource: "upload",
    useCamera: "Use Camera",
    userLabel: "You",
    viewNmtCredits: "View NMT credits",
    viewShenuteCredits: "View Shenute credits",
    welcomeDescription:
      "Start with a word, a grammar question, or an image attachment and Shenute AI will keep the conversation grounded in your Coptology work.",
    welcomeTitle: "Welcome to Shenute AI",
    writeAdminFeedback: "Write admin feedback before sending.",
    play: "Speak",
    stop: "Stop",
  },
  nl: {
    accessRequired: "Meld u aan om Shenute AI te gebruiken.",
    addImage: "Afbeelding toevoegen",
    adminNotePlaceholder:
      "Alleen voor beheerders: voeg gecorrigeerde uitleg toe bij deze prompt en dit antwoord.",
    adminNoteSummary: "Leer-notitie voor beheerder",
    aiMode: "Antwoordstijl",
    aiModeDescription: "Kies hoe Shenute diepgang en snelheid moet afwegen.",
    answerStyleControls: "Antwoordstijl wijzigen",
    assistantLabel: "Shenute",
    attachmentHelp:
      "Shenute leest deze afbeelding met OCR wanneer u uw bericht verzendt.",
    attachmentName: "Bestand",
    attachmentReady: "Afbeelding klaar voor OCR",
    attachmentSize: "Grootte",
    cameraCapture: "Afbeelding vastleggen",
    cameraClose: "Camera sluiten",
    cameraFrameFailed: "Het camerabeeld kon niet worden vastgelegd.",
    cameraImageFailed:
      "De afbeelding kon niet vanuit de camera worden vastgelegd.",
    cameraNotReady: "De camera is nog niet klaar.",
    cameraPreview: "Cameravoorbeeld",
    cameraNotSupported:
      "De camera wordt niet ondersteund op dit apparaat of in deze browser.",
    cameraStillLoading: "De camerafeed is nog niet klaar. Probeer het opnieuw.",
    cameraSource: "camera",
    cancelResponse: "Antwoord stoppen",
    closeMenu: "Menu sluiten",
    closeAnswerStyleControls: "Antwoordstijl sluiten",
    copiedResponse: "Gekopieerd.",
    conversationActions: "Gespreksacties",
    conversationHistory: "Gespreksgeschiedenis",
    copyResponse: "Kopiëren",
    copyResponseFailed: "Kopiëren is mislukt.",
    copyResponseManual: "Handmatig kopiëren.",
    copyResponseManualHint:
      "Klembordtoegang is geblokkeerd in deze browser. Selecteer de antwoordtekst hieronder en kopieer die handmatig.",
    creditsLinkDescription:
      "Credits, technische notities en onderzoeksvermeldingen staan nu op de bijdragerspagina.",
    creditsLinkTitle: "Credits en technische notities",
    creditsShort: "Credits",
    dangerZone: "Risicozone",
    dislike: "Niet behulpzaam",
    feedbackPromptMissing:
      "De prompt en het antwoord voor deze feedback konden niet worden bepaald.",
    feedbackSaved: "Bedankt voor uw feedback.",
    feedbackSavedWithRag: "Bedankt, dit helpt Shenute te verbeteren.",
    feedbackSavedLearningDelayed:
      "Bedankt voor uw feedback. De leersynchronisatie wordt later bijgewerkt.",
    feedbackSaveFailed: "Feedback kon niet worden opgeslagen.",
    feedbackSaving: "Feedback opslaan...",
    feedbackSignIn: "Meld u aan om feedback te verzenden.",
    feedbackSignInInline: "Meld u aan om antwoorden als behulpzaam te markeren",
    expandControls: "Chatbediening tonen",
    imageAttached: "Afbeelding toegevoegd",
    imageOcrContext: "[Image OCR Context]",
    intro:
      "Stel vragen over Koptische woordenschat, grammatica, vertaling en manuscriptcontext zonder de gedeelde werkruimte te verlaten.",
    jumpToLatest: "Nieuwste",
    like: "Behulpzaam",
    noTextExtracted:
      "Er is geen tekst uit de geselecteerde afbeelding gehaald.",
    ocrFailed: "OCR is mislukt voor de geselecteerde afbeelding.",
    pageContextBadge: "Pagina-context",
    placeholder:
      "Vraag naar een Koptisch woord, een grammaticaregel of een toegevoegde afbeelding...",
    placeholderImage: "Vraag naar deze afbeelding...",
    placeholderShort: "Vraag Shenute...",
    saveHistory: "Nu opslaan",
    saveHistorySaved: "Opgeslagen",
    savingHistory: "Opslaan...",
    savedHistory: "Gesprek opgeslagen.",
    saveHistoryFailed: "Dit gesprek kon niet worden opgeslagen.",
    historyUnavailable: "Gespreksgeschiedenis kon nu niet worden geladen.",
    autosaveHint: "Gesprekken worden automatisch in uw account opgeslagen.",
    autosaveStatus: "Opgeslagen in uw account.",
    unsavedChanges: "Niet-opgeslagen wijzigingen. Automatisch opslaan...",
    clearConversation: "Gesprek verwijderen",
    clearConversationConfirm:
      "Dit Shenute-gesprek verwijderen? Opgeslagen kopieën worden uit uw account verwijderd.",
    clearConversationFailed: "Dit gesprek kon niet worden verwijderd.",
    clearingConversation: "Gesprek verwijderen...",
    conversationCleared: "Gesprek verwijderd.",
    continuePrompt: "Ga verder met uw vorige antwoord.",
    continueResponse: "Antwoord vervolgen",
    newConversation: "Nieuwe chat starten",
    newConversationStarted: "Nieuwe chat gestart.",
    thinking: "Denkt na",
    thinkingComposing: "Antwoord opstellen",
    thinkingElapsed: "Verstreken",
    thinkingInitial: "Antwoord voorbereiden",
    thinkingLong: "Nog bezig",
    thinkingLongHint: "Grotere Koptische vragen kunnen even duren.",
    thinkingSearching: "Bronnen controleren",
    loadSession: "Laden",
    currentSession: "Huidig",
    loadingSession: "Sessieweergave laden...",
    sessionCount: "sessies",
    sessionDateMissing: "Geen tijdstempel",
    sessionUnsavedBadge: "Niet opgeslagen",
    providerGemini: "Snel antwoord",
    providerGeminiDescription:
      "Gebruik Gemini's eigen voorkennis met opgehaalde context als optionele steun.",
    providerGeminiNmt: "Snel antwoord (RAG + NMT)",
    providerGeminiNmtDescription:
      "Gemini met strikte contextverankering en NMT-vertaalsuggesties.",
    providerHf: "Experimenteel",
    providerHfDescription: "Een lichtere experimentele vergelijking.",
    providerOpenRouter: "Uitgewerkt antwoord",
    providerOpenRouterDescription:
      "Meer stapsgewijze structuur voor moeilijkere vragen.",
    providerThoth: "Beste antwoord",
    providerThothDescription:
      "De sterkste standaard voor Koptologische vragen.",
    ragWarning: "Opgeslagen, maar de leersynchronisatie waarschuwde:",
    rateLimit: "Shenute is nu bezet. Wacht even en probeer het opnieuw.",
    regenerateResponse: "Opnieuw genereren",
    remove: "Verwijderen",
    requestFailed:
      "Shenute heeft nu moeite met antwoorden. Probeer het zo opnieuw.",
    responseActions: "Antwoordacties",
    responseFeedbackActions: "Feedback",
    responseReviseActions: "Antwoord aanpassen",
    responseUseActions: "Antwoord gebruiken",
    runningOcr: "OCR uitvoeren...",
    selectCopyText: "Tekst selecteren",
    sendMessage: "Bericht verzenden",
    selectedImageAlt: "Geselecteerd voor OCR",
    submitAdminNote: "Beheerdersnotitie sturen",
    starterPromptsTitle: "Probeer Shenute",
    starterPromptGrammar: "Leg uit hoe het Bohairische bepaald lidwoord werkt.",
    starterPromptImage: "Help me een Koptische manuscriptfoto te lezen.",
    starterPromptTranslate:
      "Vertaal “Jezus Christus is opgestaan” naar Bohairisch-Koptisch.",
    title: "Shenute AI",
    uploadSource: "upload",
    useCamera: "Camera gebruiken",
    userLabel: "U",
    viewNmtCredits: "Bekijk NMT-credits",
    viewShenuteCredits: "Bekijk Shenute-credits",
    welcomeDescription:
      "Begin met een woord, een grammaticavraag of een afbeelding. Shenute AI houdt het gesprek verbonden met uw Koptologiewerk.",
    welcomeTitle: "Welkom bij Shenute AI",
    writeAdminFeedback: "Schrijf beheerdersfeedback voordat u die verstuurt.",
    play: "Spreken",
    stop: "Stop",
  },
} as const satisfies Record<Language, Record<string, string>>;

export type ShenuteCopy = {
  [Key in keyof (typeof SHENUTE_COPY)["en"]]: string;
};
